### ISSUE TITLE
How to generate files statically?

### ISSUE THREAD

**Issue by PhilipRoman** [mimoduo/Mimogear#1]
Maybe this is more of a gulp question than mimogear, but how do I generate resulting files as static html+css?

**Comment by mimoduo** [comment]
Hey there @PhilipRoman ,

**First off, thank you for trying out Mimogear!**

All the stuff from the get go is pug+sass so you'll wanna install all the compiler dependencies:

- Whip open a terminal,
- `cd` (change current directory) into your mimogear project directory,
- run `sudo npm install gulp-cli -g` if haven't used gulp before (the sudo is for OSX)
- run `npm install` to install all of mimogear's dependencies
- run gulp to finally generate html+css!

There's also some supplementary documentation to get you going as well:
https://github.com/mimoduo/mimogear/tree/master/docs

If you run into any issues let me know on this thread and we can go from there.

_Good luck!_

Sincerely,
Mimoduo

**Comment by PhilipRoman** [comment]
Ah, what confused me was that output files were being placed at project root! Because I didn't find a "build"/"web"/"out" folder, I was assuming that the default gulp task was simply serving the files without placing them on filesystem!
